services:
  pythonapp:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: certi-tester-pythonapp
    restart: always
    ports:
      - '7784:7784'
    command: sh -c "sleep 30s ; gunicorn -w 4 -b 0.0.0.0:7784 app:app"
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: certi-tester-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'certi_tsi'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local