name: Docker CI/CD

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Stop and remove all running containers
        run: |
          docker ps -q | xargs -r docker stop
          docker ps -aq | xargs -r docker rm

      - name: Build and tag Docker images
        run: |
          docker-compose up --build -d
          sleep 10 

      - name: Tagging the built images
        run: |
          docker tag certi-tester-pythonapp sundaydied/certi-tester:pythonapp
          docker tag certi-tester-mysql sundaydied/certi-tester:mysql

      - name: Push Docker images to Docker Hub
        run: |
          docker push sundaydied/certi-tester:pythonapp
          docker push sundaydied/certi-tester:mysql
      
      - name: Taking the docker container down
        run: | 
          docker-compose down
